openapi: 3.0.3
info:
  title: Todo List
  description: API de gerenciamento de tarefas
  version: 1.0.0
  contact:
    email: 101366@aluno.uricer.edu.br
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /tarefa/post:
    post:
      summary: Adiciona uma nova tarefa
      operationId: addTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskInput'
      responses:
        '201':
          description: Tarefa adicionada ao banco de dados 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Requisição inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Erro interno do servidor
  /tarefa:
    get:
      summary: Lista todas as tarefas
      operationId: listTasks
      responses:
        '200':
          description: Lista de tarefas obtida com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '500':
          description: Erro interno do servidor
  /tarefa/{id}:
    get:
      summary: Retorna tarefa com base no ID
      operationId: getTaskById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID da tarefa
      responses:
        '200':
          description: Tarefa retornada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Tarefa não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Erro interno do servidor
    delete:
      summary: Deleta uma tarefa com base no ID
      operationId: deleteTask
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID da tarefa a ser deletada
      responses:
        '200':
          description: Tarefa deletada
        '404':
          description: Tarefa não encontrada
        '500':
          description: Erro interno do servidor
    put:
      summary: Atualiza uma tarefa existente com base no ID
      operationId: updateTask
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID da tarefa a ser atualizada
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Tarefa atualizada 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Requisição inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Tarefa não encontrada
        '500':
          description: Erro interno do servidor
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID da tarefa
        descricao:
          type: string
          description: Descrição da tarefa
        dataCriacao:
          type: string
          format: date
          description: Data de criação da tarefa
        dataLimite:
          type: string
          format: date
          description: Data limite para a conclusão da tarefa
        finalizada:
          type: boolean
          description: Indica se a tarefa está concluída ou não
      example:
        id: 1
        descricao: Ler Mangá
        dataCriacao: "2024-05-26T10:18:02"
        dataLimite: "2024-05-30"
        finalizada: false
    TaskInput:
      type: object
      properties:
        descricao:
          type: string
          description: Descrição da tarefa
        dataCriacao:
          type: string
          format: date
          description: Data de criação da tarefa
        dataLimite:
          type: string
          format: date
          description: Data limite para a conclusão da tarefa
        finalizada:
          type: boolean
          description: Indica se a tarefa está concluída
      required:
        - descricao
        - criacao
        - limite
        - finalizada
      example:
        descricao: Ler Livro
        dataCriacao: "2024-05-26T10:18:02"
        dataLimite: "2024-06-01T23:19:02"
        finalizada: false
    TaskUpdate:
      type: object
      properties:
        descricao:
          type: string
          description: Descrição da tarefa
        dataCriacao:
          type: string
          format: date
          description: Data de criação da tarefa
        dataLimite:
          type: string
          format: date
          description: Data limite para a conclusão da tarefa
        finalizada:
          type: boolean
          description: Indica se a tarefa está concluída
      required:
        - descricao
        - criacao
        - limite
        - finalizada
      example:
        descricao: Ler Manga
        dataCriacao: "2024-05-26T10:18:02"
        dataLimite: "2024-06-01T23:19:02"
        finalizada: true
    Error:
      type: object
      properties:
        message:
          type: string
          description: Mensagem de erro